"""Core numerical kernels and assembly helpers."""

from .angular import uniform_periodic_azimuth_grid, uniform_polar_grid
from .fields import (
    AngularSpectrumSource,
    BesselBeam,
    CartesianPolarizedBesselBeam,
    CartesianPolarizedFocusedLaguerreGaussianBeam,
    DipoleCollection,
    DipoleSource,
    FocusedLaguerreGaussianBeam,
    GaussianBeam,
    JonesPolarizedSource,
    LaguerreGaussianBeam,
    PlaneWave,
    SLMSource,
    Source,
    angular_spectrum_to_svwf_regular,
    polarization_to_jones,
    project_source_basis_to_svwf,
    project_source_to_svwf,
    pwp_to_svwf_regular,
    svwf_outgoing_to_pwp,
    svwf_regular_to_pwp,
)
from .matvec import (
    PreparedMatvec,
    apply_A_numpy,
    apply_W_numpy,
    assemble_dense_A_numpy,
    estimate_translation_cache_bytes,
    make_prepared_A_and_rhs,
    precompute_T_diagonal,
    precompute_T_diagonal_from_particles,
    prepare_matvec,
    prepare_matvec_from_particles,
    rhs_Tb_numpy,
)
from .particles import Ellipsoid, LayeredSphere, Particle, Sphere
from .tmatrix import (
    layered_internal_ab_ratios,
    layered_mie_ab,
    layered_sphere_T_diagonal,
    particle_internal_ratios,
    particle_T_diagonal,
)

__all__ = [
    "Ellipsoid",
    "AngularSpectrumSource",
    "BesselBeam",
    "CartesianPolarizedBesselBeam",
    "CartesianPolarizedFocusedLaguerreGaussianBeam",
    "DipoleSource",
    "DipoleCollection",
    "FocusedLaguerreGaussianBeam",
    "JonesPolarizedSource",
    "uniform_periodic_azimuth_grid",
    "uniform_polar_grid",
    "GaussianBeam",
    "LaguerreGaussianBeam",
    "SLMSource",
    "LayeredSphere",
    "Particle",
    "PlaneWave",
    "Source",
    "PreparedMatvec",
    "Sphere",
    "assemble_dense_A_numpy",
    "apply_A_numpy",
    "apply_W_numpy",
    "estimate_translation_cache_bytes",
    "make_prepared_A_and_rhs",
    "particle_T_diagonal",
    "particle_internal_ratios",
    "layered_mie_ab",
    "layered_sphere_T_diagonal",
    "layered_internal_ab_ratios",
    "precompute_T_diagonal",
    "precompute_T_diagonal_from_particles",
    "prepare_matvec",
    "prepare_matvec_from_particles",
    "pwp_to_svwf_regular",
    "angular_spectrum_to_svwf_regular",
    "svwf_regular_to_pwp",
    "svwf_outgoing_to_pwp",
    "polarization_to_jones",
    "project_source_to_svwf",
    "project_source_basis_to_svwf",
    "rhs_Tb_numpy",
]
